$PROB TESTING RANDOM SAMPLERS
$ABBR FUNCTION rayleigh(VQI,10)
$ABBR VECTOR VV(10)
$INPUT  AMT TVAL DV
$DATA  rsampler.csv

$PRED
ALPHA=theta(1)
IF(ICALL==4) THEN
VV(1)=1.0
VV(2)=ALPHA
" CALL rayleigh_RNG(2,VV)
Y=VV(1)
DV=Y
ELSE
VQI(1)=DV
VQI(2)=ALPHA
WW=rayleigh(VQI)
Y=2.0*WW
ENDIF

$THETA (0.0,5.0) 

$SIMULATION (567811 NORMAL) (2933012 UNIFORM) (445678 NORMAL) SUBPROBLEMS=1 
$EST METHOD=0 MAXEVAL=9999 PRINT=1 -2LL NOTHETABOUNDTEST 
$COVR
$TABLE TVAL DV NOAPPEND NOPRINT FILE=ran_rayleigh.tab
