call dosome2.bat example2
call dosome2.bat example5
call dosome2.bat example8
call dosome2.bat example9
call dosome2.bat superid3_6
call dosome2.bat tdist7
call dosome2.bat sde9
call dosome2.bat idr_circexa
call dosome2.bat infnexa1
call dosome2.bat infnexa2
call dosome2.bat ssmultidose
call dosome2.bat ssonedose
call dosome2.bat step_circexa
call dosome2.bat indestb
call dosome2.bat indestm
call dosome2.bat indestms
