call dosome2.bat anneal
call dosome2.bat anneal2
call dosome2.bat anneal3
call dosome2.bat anneal4
call dosome2.bat anneal5
call dosome2.bat annealq
call dosome2.bat ar1mod
call dosome2.bat ar1newsim
call dosome2.bat example10
call dosome2.bat example10l
call dosome2.bat example8b
call dosome2.bat repeat1
call dosome2.bat repeat1s
call dosome2.bat repeat1t
call dosome2.bat repeatf
call dosome2.bat sde
call dosome2.bat thetair
