! THIS EXAMPLE IS ADAPTED FROM GUIDE VI (PREDPP), FIGURE 37.
! FOR HELP FILE infn1.exa
! MODIFIED BY AJB 9/2012
 ! INFN ROUTINE FOR COMPUTING LINEARLY INTERPOLATED VALUES
 ! OF AN INDEPENDENT VARIABLE V.    ILLUSTRATES USE OF ROUTINE PASS.
 ! USE FOR SINGLE-SUBJECT OR POPULATION DATA
 ! WORKS WITH 1 OR MORE NON-MISSING VALUES. 
 ! A SINGLE SUCH VALUE MAY BE ANYWHERE IN DATA SET.
 ! DATREC(UI)=TIME DATA ITEM
 ! DATREC(VI)=INDEPENDENT VARIABLE DATA ITEM
 ! DATREC(MI)=MISSING INDEPENDENT VARIABLE DATA ITEM
 !   =0 INDEP VAR NOT MISSING
 !   >0 IF THIS DATA RECORD HAS MISSING INDEP VAR AND:
 !   =1    THIS DATA RECORD PRECEDES FIRST NON-MISSING VALUE
 !   =3    THIS DATA RECORD FOLLOWS LAST NON-MISSING VALUE
 !   =2    THIS DATA RECORD IS BETWEEN NON-MISSING VALUES
 !
       SUBROUTINE INFN (ICALL,THETA,DATREC,INDXS,NEWIN)
       USE SIZES, ONLY: ISIZE,DPSIZE,NO,MAXIDS
! NOTE THAT NEWIND IS NOT OBTAINED FROM THE SUBROUTINE ARGUMENT
       USE NMPRD_INT, ONLY: NEWIND=>NWIND
       INTEGER(KIND=ISIZE), INTENT(IN) :: ICALL,INDXS(*),NEWIN
       REAL(KIND=DPSIZE),   INTENT(IN) :: THETA(*)
       REAL(KIND=DPSIZE),   INTENT(IN OUT) :: DATREC(*)
       REAL(KIND=DPSIZE) :: U,V
       DIMENSION U(NO,MAXIDS),V(NO,MAXIDS),DEPVAR(MAXIDS),LASTI(MAXIDS)
       INTEGER UI,VI,MI,IS,LASTI
! IMPORTANT: CHANGE UI, VI, MI ACCORDING TO LAYOUT OF DATA SET
       UI=3
       VI=5
       MI=6
! 
       IF (ICALL.NE.1) RETURN
       I=0
       IS=0
 ! INITIALIZE PASS
       MODE=0
       CALL PASS (MODE)
       MODE=2
 ! PASS THROUGH DATA
     5 CALL PASS (MODE)
       IF (MODE.EQ.0) GO TO 10
       IF (NEWIND<2) THEN
         I=0
         IS=IS+1
       ENDIF
 ! IF INDEP VAR IS PRESENT, STORE TIME AND VALUE
       IF (DATREC(MI).EQ.0.) THEN
          I=I+1
          U(IS,I)=DATREC(UI)
          V(IS,I)=DATREC(VI)
          LASTI(IS)=I
       ENDIF
       IF (I == 1) THEN   ! SAVE VALUE IN CASE ONLY RECORDED ONCE
          DEPVAR(IS)=V(IS,1)
       ENDIF
       GO TO 5
 ! INITIALIZE PASS A SECOND TIME
    10 I=0
       IS=0
       MODE=0
       CALL PASS (MODE)
       MODE=2
 ! PASS THROUGH DATA A SECOND TIME
    15 CALL PASS (MODE)
       IF (MODE.EQ.0) RETURN
       IF (NEWIND<2) THEN
         I=0
         IS=IS+1
       ENDIF
! IF INDEP VAR IS MISSING AND ONLY RECORDED ONCE, COPY IT
       IF (DATREC(MI).NE.0. .AND. LASTI(IS) == 1 ) THEN
        DATREC(VI)=DEPVAR(IS)
        GO TO 15
       ENDIF
 ! IF INDEP VAR IS MISSING, STORE INTERPOLATED VALUE
       IF (DATREC(MI).EQ.0.) THEN
          I=I+1
       ELSE
          IF (DATREC(MI).EQ.1.) THEN   ! EXTRAPOLATE FROM FIRST 2 VALUES
             K=1
             L=2
          ELSEIF (DATREC(MI).EQ.2.) THEN  ! INTERPOLATE FROM VALUES BEFORE AND AFTER
             K=I
             L=I+1
          ELSEIF (DATREC(MI).EQ.3.) THEN   ! EXTRAPOLATE FROM LAST 2 VALUES
             K=I-1
             L=I
          ENDIF
          B=(V(IS,K)-V(IS,L))/(U(IS,K)-U(IS,L))
          DATREC(VI)=V(IS,K)+B*(DATREC(UI)-U(IS,K))
       ENDIF
       GO TO 15
       END
