      SUBROUTINE THETAISUB(THETAI,THETA,THETAPI,THETAP)
      USE NMPRD_INT,    ONLY: NTHETA,NTHP=>NTHPT,NTHPTDIM,NPROB,IPROB
      IMPLICIT NONE
      REAL*8, INTENT(IN) :: THETAI(NTHETA+NTHPTDIM),THETAPI(NTHPTDIM)
      REAL*8 THETA(NTHETA+NTHPTDIM),THETAP(NTHPTDIM)
      
      THETA(4:5)=LOG(EXP(THETAI(4:5))+1.0)
      THETA(9:10)=LOG(EXP(THETAI(9:10))+1.0)
      RETURN
      END
      SUBROUTINE THETARSUB(THETA,THETAR,THETAP,THETAPR)
      USE NMPRD_INT,    ONLY: NTHETA,NTHP=>NTHPT,NTHPTDIM,NPROB,IPROB
      IMPLICIT NONE
      REAL*8 THETAR(NTHETA+NTHPTDIM),THETAPR(NTHPTDIM)
      REAL*8, INTENT(IN) :: THETA(NTHETA+NTHPTDIM),THETAP(NTHPTDIM)
      
      THETAR(4:5)=LOG(EXP(THETA(4:5))-1.0)
      THETAR(9:10)=LOG(EXP(THETA(9:10))-1.0)
      RETURN
      END
